"use client";
/*
 * src/components/features/PublicOutputActions.tsx
 *
 * Client component for the public output page action buttons:
 *  - Copy link
 *  - Copy for LinkedIn
 *  - Export as DOC
 *  - Export as PDF
 */

import { useState } from "react";

interface PublicOutputActionsProps {
  shareUrl: string;
  content: string;
  outputType: string;
  title: string;
}

function downloadAsDoc(content: string, filename: string) {
  const blob = new Blob([content], { type: "application/msword" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = `${filename}.doc`; a.click();
  URL.revokeObjectURL(url);
}

function printAsPdf(content: string, title: string) {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`<!DOCTYPE html><html><head><title>${title}</title>
  <style>
    body{font-family:Georgia,serif;max-width:720px;margin:40px auto;line-height:1.7;color:#1f2328;font-size:15px}
    h1{font-size:22px;margin-bottom:4px}
    .meta{color:#57606a;font-size:13px;margin-bottom:32px}
    h2{font-size:17px;margin-top:28px;border-top:1px solid #e5e7eb;padding-top:12px}
    p{margin:8px 0}
    @media print{body{margin:20px}}
  </style></head><body>
  <h1>${title}</h1>
  <div class="meta">Generated by SkillNarrate</div>
  ${content.split("\n").map((l)=>
    l.startsWith("## ")?`<h2>${l.slice(3)}</h2>`:
    l.trim()===""?"<br/>":
    `<p>${l.replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>")}</p>`
  ).join("")}
  </body></html>`);
  win.document.close();
  win.print();
}

export default function PublicOutputActions({
  shareUrl,
  content,
  outputType,
  title,
}: PublicOutputActionsProps) {
  const [copyLinkDone,    setCopyLinkDone]    = useState(false);
  const [copyContentDone, setCopyContentDone] = useState(false);

  const copyText = async (text: string, setDone: (v: boolean) => void) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    }
    setDone(true);
    setTimeout(() => setDone(false), 2000);
  };

  return (
    <div className="flex flex-wrap gap-3 items-center">
      {/* Copy link */}
      <button
        onClick={() => copyText(shareUrl, setCopyLinkDone)}
        className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-gray-200 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        {copyLinkDone ? "✓ Copied!" : "🔗 Copy Link"}
      </button>

      {/* LinkedIn copy */}
      {outputType === "linkedin_post" && (
        <button
          onClick={() => copyText(content, setCopyContentDone)}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-medium transition-colors"
          style={{ borderColor: "#0077b5", color: "#0077b5", backgroundColor: "#fff" }}
        >
          {copyContentDone ? "✓ Copied!" : "💼 Copy for LinkedIn"}
        </button>
      )}

      {/* Export DOC */}
      <button
        onClick={() => downloadAsDoc(content, title)}
        className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-gray-200 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        📄 Export DOC
      </button>

      {/* Export PDF */}
      <button
        onClick={() => printAsPdf(content, title)}
        className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-gray-200 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        🖨 Export PDF
      </button>
    </div>
  );
}
