-- ============================================================
-- SkillNarrate — Institutions Seed Data
-- Migration: 20240101000003_seed_institutions.sql
-- ============================================================
-- Source: HELB/TVETA Approved TVET Institutions List (Kenya)
-- 180 institutions across National Polytechnics, TTIs/TVCs,
-- and Institutes of Technology.
--
-- HOW TO RUN THIS:
-- Option A (Dashboard): Supabase Dashboard → SQL Editor → paste & run
-- Option B (CLI): supabase db push  (if you have supabase CLI set up)
-- Option C (psql): psql $DATABASE_URL -f this_file.sql
--
-- WHY ON CONFLICT DO NOTHING?
-- If you run this script more than once (e.g. resetting dev DB),
-- the UNIQUE constraint on institutions.name would cause an error.
-- ON CONFLICT DO NOTHING tells Postgres to skip rows that already exist
-- instead of erroring out. Safe to run multiple times.
--
-- HOW WAS THIS GENERATED?
-- The raw PDF/text list was parsed programmatically and cleaned by hand.
-- Each row follows: (name, nearest_town, county, category)
-- ============================================================

INSERT INTO institutions (name, nearest_town, county, category) VALUES

-- ── National Polytechnics (12) ────────────────────────────────
('Eldoret National Polytechnic',                              'Eldoret',          'Uasin Gishu',       'National Polytechnic'),
('Kabete National Polytechnic',                               'Kabete',           'Kiambu',            'National Polytechnic'),
('Kenya Coast National Polytechnic',                          'Tononoka',         'Mombasa',           'National Polytechnic'),
('Kenya School of TVET',                                      'Gigiri',           'Nairobi',           'National Polytechnic'),
('Kisii National Polytechnic',                                'Kisii',            'Kisii',             'National Polytechnic'),
('Kisumu National Polytechnic',                               'Kisumu',           'Kisumu',            'National Polytechnic'),
('Kitale National Polytechnic',                               'Kitale',           'Trans Nzoia',       'National Polytechnic'),
('Meru National Polytechnic',                                 'Meru',             'Meru',              'National Polytechnic'),
('North Eastern National Polytechnic',                        'Garissa',          'Garissa',           'National Polytechnic'),
('Nyandarua National Polytechnic',                            'Nyahururu',        'Nyandarua',         'National Polytechnic'),
('Nyeri National Polytechnic',                                'Nyeri',            'Nyeri',             'National Polytechnic'),
('Sigalagala National Polytechnic',                           'Sigalagala',       'Kakamega',          'National Polytechnic'),

-- ── Technical Training Institutes & Vocational Colleges (161) ─
('Ahmed Shahame Mwidani Technical Training Institute',        'Changamwe',        'Mombasa',           'TTI/TVC'),
('Aldai Technical Training Institute',                        'Kobujoi',          'Nandi',             'TTI/TVC'),
('Baringo Technical College',                                 'Kabarnet',         'Baringo',           'TTI/TVC'),
('Belgut Technical and Vocational College',                   'Kericho',          'Kericho',           'TTI/TVC'),
('Bomet Central Technical and Vocational College',            'Bondet',           'Bomet',             'TTI/TVC'),
('Bondo Technical Training Institute',                        'Bondo',            'Siaya',             'TTI/TVC'),
('Borabu Technical and Vocational College',                   'Nyansiongo',       'Nyamira',           'TTI/TVC'),
('Bumbe Technical Training Institute',                        'Bwiri',            'Busia',             'TTI/TVC'),
('Bungoma North Technical and Vocational College',            'Kimilili',         'Bungoma',           'TTI/TVC'),
('Bunyala Technical and Vocational College',                  'Port Victoria',    'Busia',             'TTI/TVC'),
('Bureti Technical Training Institute',                       'Sotik',            'Bomet',             'TTI/TVC'),
('Bushiangala Technical Training Institute',                  'Bushiangala',      'Kakamega',          'TTI/TVC'),
('Butere Technical and Vocational College',                   'Butere',           'Kakamega',          'TTI/TVC'),
('Chamasiri Technical and Vocational College',                'Malakisi',         'Busia',             'TTI/TVC'),
('Chanzeywe Technical and Vocational College',                'Luanda',           'Vihiga',            'TTI/TVC'),
('Chepalungu Technical Training Institute',                   'Chebunyo',         'Bomet',             'TTI/TVC'),
('Chepsirei Technical and Vocational College',                'Kimwarer',         'Elgeyo Marakwet',   'TTI/TVC'),
('Cherangany Technical and Vocational College',               'Cherangany',       'Trans Nzoia',       'TTI/TVC'),
('Chuka Technical and Vocational College',                    'Chuka',            'Tharaka Nithi',     'TTI/TVC'),
('David M. Wambuli Technical and Vocational College',         'Kakalia',          'Makueni',           'TTI/TVC'),
('Dr. Daniel Wako Murende Technical and Vocational College',  'Matayos',          'Busia',             'TTI/TVC'),
('Ebukanga Technical and Vocational College',                 'Luanda',           'Vihiga',            'TTI/TVC'),
('Ekerubo Gietai Technical Training Institute',               'Ikonge',           'Nyamira',           'TTI/TVC'),
('Eldama Ravine Technical and Vocational College',            'Eldama Ravine',    'Baringo',           'TTI/TVC'),
('Emining Technical Training Institute',                      'Mogotio',          'Baringo',           'TTI/TVC'),
('Emsos Technical and Vocational College',                    'Mosoriot',         'Nandi',             'TTI/TVC'),
('Emgwen Technical and Vocational College',                   'Arwos',            'Nandi',             'TTI/TVC'),
('Emurua Dikirr Technical Training Institute',                'Chebunyo',         'Narok',             'TTI/TVC'),
('Endebess Technical Training Institute',                     'Endebess',         'Trans Nzoia',       'TTI/TVC'),
('Gatanga Technical and Vocational College',                  'Gatanga',          'Murang''a',         'TTI/TVC'),
('Gatundu South Technical and Vocational College',            'Ngenda',           'Kiambu',            'TTI/TVC'),
('Gitwebe Technical Training Institute',                      'Magwagwa',         'Nyamira',           'TTI/TVC'),
('Heroes Technical and Vocational College',                   'Bahati',           'Nakuru',            'TTI/TVC'),
('Godoma Technical Training Institute',                       'Vitengeni',        'Kilifi',            'TTI/TVC'),
('Ikutha Technical and Vocational College',                   'Ikutha Market',    'Kitui',             'TTI/TVC'),
('Jeremiah Nyaga Technical Training Institute',               'Kiritiri',         'Embu',              'TTI/TVC'),
('Kaelo Technical and Vocational College',                    'Laare',            'Meru',              'TTI/TVC'),
('Kaiboi Technical Training Institute',                       'Mosoriot',         'Nandi',             'TTI/TVC'),
('Kajiado East Technical and Vocational College',             'Kitengela',        'Kajiado',           'TTI/TVC'),
('Kajiado West Technical and Vocational College',             'Ngong',            'Kajiado',           'TTI/TVC'),
('Kakrao Technical and Vocational College',                   'Kakrao',           'Migori',            'TTI/TVC'),
('Kamukunji Technical and Vocational College',                'Eastleigh',        'Nairobi',           'TTI/TVC'),
('Kandara Technical and Vocational College',                  'Kandara',          'Murang''a',         'TTI/TVC'),
('Kapcherop Technical and Vocational College',                'Kapcherop',        'Elgeyo Marakwet',   'TTI/TVC'),
('Karen Technical Training Institute for the Deaf',           'Karen',            'Nairobi',           'TTI/TVC'),
('Karumo Technical Training Institute',                       'Kianjai',          'Meru',              'TTI/TVC'),
('Kasarani Technical and Vocational College',                 'Kamulu',           'Nairobi',           'TTI/TVC'),
('Katine Technical Training Institute',                       'Tala',             'Machakos',          'TTI/TVC'),
('Kendege Technical and Vocational College',                  'Kehancha',         'Migori',            'TTI/TVC'),
('Kericho Township Technical and Vocational College',         'Kericho',          'Kericho',           'TTI/TVC'),
('Kerio Valley Technical and Vocational College',             'Kapsowar',         'Elgeyo Marakwet',   'TTI/TVC'),
('Keroka Technical Training Institute',                       'Keroka',           'Kisii',             'TTI/TVC'),
('Kibwezi West Technical and Vocational College',             'Makindu',          'Makueni',           'TTI/TVC'),
('Kieni Technical and Vocational College',                    'Ndathi',           'Nyeri',             'TTI/TVC'),
('Kigumo Technical Training Institute',                       'Kigumo',           'Murang''a',         'TTI/TVC'),
('Kiirua Technical Training Institute',                       'Kiirua',           'Meru',              'TTI/TVC'),
('Kimasian Technical and Vocational College',                 'Londiani',         'Kericho',           'TTI/TVC'),
('Kiminini Technical and Vocational College',                 'Kiminini',         'Trans Nzoia',       'TTI/TVC'),
('Kinango Technical and Vocational College',                  'Mackinnon',        'Kwale',             'TTI/TVC'),
('Kinangop Technical and Vocational College',                 'Githioro',         'Nyandarua',         'TTI/TVC'),
('Kipipiri Technical and Vocational College',                 'Mawingu Town',     'Nyandarua',         'TTI/TVC'),
('Kipkabus Technical and Vocational College',                 'Kipkabus',         'Uasin Gishu',       'TTI/TVC'),
('Kipsinende Technical and Vocational College',               'Fort-Ternan',      'Kericho',           'TTI/TVC'),
('Kipsoen Technical and Vocational College',                  'Chepkinoiyo',      'Elgeyo Marakwet',   'TTI/TVC'),
('Kiptaragon Technical and Vocational College',               'Olenguruone',      'Nakuru',            'TTI/TVC'),
('Kisiwa Technical Training Institute',                       'Kabuchai',         'Bungoma',           'TTI/TVC'),
('Kitelakapel Technical Training Institute',                  'Kitelakapel',      'West Pokot',        'TTI/TVC'),
('Kitutu Masaba Technical and Vocational College',            'Birongo Market',   'Nyamira',           'TTI/TVC'),
('Kongoni Technical and Vocational College',                  'Matunda',          'Trans Nzoia',       'TTI/TVC'),
('Konoin Technical Training Institute',                       'Koiwa',            'Bomet',             'TTI/TVC'),
('Koshin Technical Training Institute',                       'Eldoret',          'Uasin Gishu',       'TTI/TVC'),
('Laikipia East Technical and Vocational College',            'Marina Center',    'Laikipia',          'TTI/TVC'),
('Laikipia North Technical and Vocational College',           'Mowuarak Market',  'Laikipia',          'TTI/TVC'),
('Laisamis Technical and Vocational College',                 'Laisamis',         'Marsabit',          'TTI/TVC'),
('Lari Technical and Vocational College',                     'Githirioni',       'Kiambu',            'TTI/TVC'),
('Likoni Technical and Vocational College',                   'Likoni',           'Mombasa',           'TTI/TVC'),
('Limuru Technical and Vocational College',                   'Limuru',           'Kiambu',            'TTI/TVC'),
('Lodwar Technical and Vocational College',                   'Lodwar',           'Turkana',           'TTI/TVC'),
('Lungalunga Technical and Vocational College',               'Lungalunga',       'Kwale',             'TTI/TVC'),
('Maasai Mara Technical and Vocational College',              'Narok',            'Narok',             'TTI/TVC'),
('Mabera Technical and Vocational College',                   'Isebania',         'Migori',            'TTI/TVC'),
('Machakos Technical Training Institute for the Blind',       'Machakos',         'Machakos',          'TTI/TVC'),
('Mandera Technical Training Institute',                      'Mandera',          'Mandera',           'TTI/TVC'),
('Manyatta Technical and Vocational College',                 'Manyatta',         'Embu',              'TTI/TVC'),
('Masai Technical Training Institute',                        'Kajiado',          'Kajiado',           'TTI/TVC'),
('Masinga Technical and Vocational College',                  'Masinga',          'Machakos',          'TTI/TVC'),
('Mathenge Technical Training Institute',                     'Othaya',           'Nyeri',             'TTI/TVC'),
('Mathioya Technical and Vocational College',                 'Kiria-ini',        'Murang''a',         'TTI/TVC'),
('Mathira Technical and Vocational College',                  'Mathira',          'Nyeri',             'TTI/TVC'),
('Matili Technical Training Institute',                       'Kimilili',         'Bungoma',           'TTI/TVC'),
('Mawego Technical Training Institute',                       'Oyugis',           'Homa Bay',          'TTI/TVC'),
('Merti Technical and Vocational College',                    'Merti',            'Isiolo',            'TTI/TVC'),
('Michuki Technical Training Institute',                      'Kangema',          'Murang''a',         'TTI/TVC'),
('Mitunguu Technical Training Institute',                     'Mitunguu',         'Meru',              'TTI/TVC'),
('Mochongoi Technical and Vocational College',                'Kabel',            'Baringo',           'TTI/TVC'),
('Moiben Technical and Vocational College',                   'Moiben',           'Uasin Gishu',       'TTI/TVC'),
('Molo Technical and Vocational College',                     'Elburgon',         'Nakuru',            'TTI/TVC'),
('Mukiria Technical Training Institute',                      'Nkubu',            'Meru',              'TTI/TVC'),
('Mukurwe-ini Technical Training Institute',                  'Gikondi',          'Nyeri',             'TTI/TVC'),
('Mumias West Technical and Vocational College',              'Mumias',           'Kakamega',          'TTI/TVC'),
('Mungatsi Technical and Vocational College',                 'Mungatsi Market',  'Busia',             'TTI/TVC'),
('Muraga Technical Training Institute',                       'Chuka',            'Tharaka Nithi',     'TTI/TVC'),
('Murang''a Technical Training Institute',                    'Maragua',          'Murang''a',         'TTI/TVC'),
('Musakasa Technical Training Institute',                     'Bungoma',          'Bungoma',           'TTI/TVC'),
('Msambweni Technical and Vocational College',                'Msambweni',        'Kwale',             'TTI/TVC'),
('Mwala Technical and Vocational College',                    'Mwala',            'Machakos',          'TTI/TVC'),
('Mwea Technical and Vocational College',                     'Wang''uru',        'Kirinyaga',         'TTI/TVC'),
('Nachu Technical and Vocational College',                    'Kikuyu',           'Kiambu',            'TTI/TVC'),
('Nairobi Technical Training Institute',                      'Ngara',            'Nairobi',           'TTI/TVC'),
('Naivasha Technical and Vocational College',                 'Naivasha',         'Nakuru',            'TTI/TVC'),
('Narok West Technical Training Institute',                   'Narok',            'Narok',             'TTI/TVC'),
('Navakholo Technical and Vocational College',                'Navakholo',        'Kakamega',          'TTI/TVC'),
('Ndaragwa Technical and Vocational College',                 'Ndaragwa',         'Nyandarua',         'TTI/TVC'),
('Ndia Technical and Vocational College',                     'Sagana',           'Kirinyaga',         'TTI/TVC'),
('Ngong Technical and Vocational College',                    'Ngong',            'Kajiado',           'TTI/TVC'),
('Njoro Technical Training Institute',                        'Njoro',            'Nakuru',            'TTI/TVC'),
('Nkabune Technical Training Institute',                      'Meru',             'Meru',              'TTI/TVC'),
('North Horr Technical and Vocational College',               'North Horr',       'Marsabit',          'TTI/TVC'),
('Nuu Technical and Vocational College',                      'Mwingi',           'Kitui',             'TTI/TVC'),
('Nyakach Technical and Vocational College',                  'Nyabondo',         'Kisumu',            'TTI/TVC'),
('Okame Technical and Vocational College',                    'Busia',            'Busia',             'TTI/TVC'),
('Ol''lessos Technical Training Institute',                   'Ol''lessos',       'Nandi',             'TTI/TVC'),
('Omuga Technical and Vocational College',                    'Kadongo',          'Homa Bay',          'TTI/TVC'),
('Orogare Technical and Vocational College',                  'Ogembo',           'Kisii',             'TTI/TVC'),
('PC Kinyanjui Technical Training Institute',                 'Riruta Satellite', 'Nairobi',           'TTI/TVC'),
('Rachuonyo Technical and Vocational College',                'Ombek',            'Homa Bay',          'TTI/TVC'),
('Rangwe Technical and Vocational College',                   'Kadel',            'Homa Bay',          'TTI/TVC'),
('Riamo Technical and Vocational College',                    'Kenyenya',         'Kisii',             'TTI/TVC'),
('Riatirimba Technical and Vocational College',               'Gesusu',           'Kisii',             'TTI/TVC'),
('Riragia Technical and Vocational College',                  'Kegogi',           'Kisii',             'TTI/TVC'),
('Rift Valley Technical Training Institute',                  'Eldoret',          'Uasin Gishu',       'TTI/TVC'),
('Runyenjes Technical and Vocational College',                'Runyenjes',        'Embu',              'TTI/TVC'),
('Sabatia Technical and Vocational College',                  'Sabatia',          'Vihiga',            'TTI/TVC'),
('Shamberere Technical Training Institute',                   'South Kabras',     'Kakamega',          'TTI/TVC'),
('Samburu Technical and Vocational College',                  'Archers Post',     'Samburu',           'TTI/TVC'),
('Seme Technical and Vocational College',                     'Kombewa',          'Kisumu',            'TTI/TVC'),
('Siala Technical Training Institute',                        'Rongo',            'Migori',            'TTI/TVC'),
('Sikri Technical and Vocational College for the Blind and Deaf', 'Oyugis',      'Homa Bay',          'TTI/TVC'),
('Sirisia Technical and Vocational College',                  'Sirisia',          'Bungoma',           'TTI/TVC'),
('Siruti Technical and Vocational College',                   'Awendo',           'Migori',            'TTI/TVC'),
('Sot Technical Training Institute',                          'Merigi',           'Bomet',             'TTI/TVC'),
('Sotik Technical Training Institute',                        'Sotik',            'Bomet',             'TTI/TVC'),
('St. Josephs Technical Institute for the Deaf-Nyangoma',     'Nyang''oma',       'Siaya',             'TTI/TVC'),
('Taveta Technical and Vocational College',                   'Taveta',           'Taita Taveta',      'TTI/TVC'),
('Tetu Technical and Vocational College',                     'Kagwathi',         'Nyeri',             'TTI/TVC'),
('Tigania East Technical and Vocational College',             'Mikinduri',        'Meru',              'TTI/TVC'),
('Tharaka Technical and Vocational College',                  'Marimanti',        'Tharaka Nithi',     'TTI/TVC'),
('Thika Technical Training Institute',                        'Thika',            'Kiambu',            'TTI/TVC'),
('Tindiret Technical and Vocational College',                 'Sigoria',          'Nandi',             'TTI/TVC'),
('Total Technical and Vocational College',                    'Total',            'Nakuru',            'TTI/TVC'),
('Tseikuru Technical Training Institute',                     'Tseikuru',         'Kitui',             'TTI/TVC'),
('Turbo Technical and Vocational College',                    'Turbo',            'Uasin Gishu',       'TTI/TVC'),
('Turkana East Technical and Vocational College',             'Lodwar',           'Turkana',           'TTI/TVC'),
('Ugenya Technical and Vocational College',                   'Sega',             'Siaya',             'TTI/TVC'),
('Ugunja Technical and Vocational College',                   'Ugunja',           'Siaya',             'TTI/TVC'),
('Wanga Technical and Vocational College',                    'Shianda',          'Kakamega',          'TTI/TVC'),
('Webuye West Technical and Vocational College',              'Webuye',           'Bungoma',           'TTI/TVC'),
('Weru Technical and Vocational College',                     'Malindi',          'Kilifi',            'TTI/TVC'),
('Wote Technical Training Institute',                         'Wote',             'Makueni',           'TTI/TVC'),
('Wumingu Technical and Vocational College',                  'Wumingu',          'Taita Taveta',      'TTI/TVC'),
('Ziwa Technical Training Institute',                         'Ziwa',             'Uasin Gishu',       'TTI/TVC'),

-- ── Institutes of Technology (7) ──────────────────────────────
('Coast Institute of Technology',                             'Voi',              'Taita Taveta',      'Institute of Technology'),
('Friends College Kaimosi',                                   'Kaimosi',          'Vihiga',            'Institute of Technology'),
('Kiambu Institute of Science and Technology',                'Ruaka',            'Kiambu',            'Institute of Technology'),
('Ramogi Institute of Advanced Technology',                   'Riat Hills',       'Kisumu',            'Institute of Technology'),
('Rift Valley Institute of Science and Technology',           'Nakuru',           'Nakuru',            'Institute of Technology'),
('Sang''alo Institute of Science and Technology',             'Bungoma',          'Bungoma',           'Institute of Technology'),
('Siaya Institute of Technology',                             'Siaya',            'Siaya',             'Institute of Technology')

ON CONFLICT (name) DO NOTHING;

-- Quick sanity check — run this after the seed to verify counts:
-- SELECT category, COUNT(*) FROM institutions GROUP BY category ORDER BY category;
-- Expected:
--   Institute of Technology  | 7
--   National Polytechnic     | 12
--   TTI/TVC                  | 161
--   Total                    | 180
